import type {
  CommerceAdAgentGuidance,
  CommerceAgentSkill,
} from '@/features/commerce-ad/types';

const AD_CREATIVE_PROMPT_INSTRUCTIONS = [
  'Skill name: 广告创意.',
  'Primary goal: design platform-native paid ad creatives for Instagram, Facebook, TikTok, LinkedIn, YouTube, Google Ads, and X.',
  'Workflow:',
  '1. First analyze all provided images: product/service identity, visible subject, scene, material/style cues, readable text, possible selling points, and uncertainty.',
  '2. Then combine image evidence with the user brief and this skill. Do not jump directly into ecommerce detail-page planning unless the user explicitly asks for detail pages.',
  '3. If platform, campaign goal, audience, offer/selling point, CTA, language, or required output format is missing, ask only the missing questions that would materially change the creative.',
  '4. Provide concrete clickable options through guidance.questions and guidance.quickReplies when information is missing.',
  '5. When enough information exists, produce ad creative strategy, platform fit, visual concept, copy options, production prompt, and a short quality check.',
  '',
  'Platform defaults:',
  '- Instagram/Facebook: feed square 1080x1080, feed portrait 1080x1350, Stories/Reels 1080x1920, landscape/link 1200x628. One message should win; keep product and hook center-safe.',
  '- TikTok: 1080x1920 vertical first. Favor creator-style hooks, motion-first story, quick product reveal, native captions.',
  '- LinkedIn: 1200x627 or 1080x1080. Lead with business pain, outcome, evidence, and restrained credible design.',
  '- YouTube: 1920x1080 for in-stream/in-feed, 1080x1920 for Shorts, 1280x720 thumbnail. Hook before skip moment; one focal point.',
  '- Google Ads: responsive display landscape 1200x628, square 1200x1200, optional vertical 900x1600. Keep imagery clean; separate headlines/descriptions from image when possible.',
  '- X: 1.91:1, 1:1, 9:16, or 16:9 variants. Make the first line/frame direct, punchy, and conversation-native.',
  '',
  'Creative patterns to consider: product hero + benefit, problem/solution split, supportable before/after, social proof from user facts, UGC/native hook, feature demo in 3 steps, offer/launch, myth/fact checklist.',
  'AI prompt rule: separate subject, brand/product constraints, scene/props, composition/crop, lighting/style, overlay text to add separately, negative constraints, and output ratio/platform.',
  'Do not rely on image generation models to render long exact text; recommend adding final copy in layout software when precision matters.',
].join('\n');

export const AD_CREATIVE_SKILL_ID = 'ad-creative';
export const AI_STYLIST_SKILL_ID = 'ai-stylist-model-conversion';

const AI_STYLIST_PROMPT_INSTRUCTIONS = [
  'Skill name: AI造型师:高转化模特图.',
  'Primary goal: plan and generate multiple professional model styling images from either product images or text-only user requirements. The skill should help the user discover strong model personas, styling categories, scenes, poses, and commercial image prompts that broaden audience reach and improve sales conversion.',
  'The user may provide no product image. In that case, do not block. Work as an AI stylist and creative director: infer likely product/category opportunities from the brief, propose model styling directions, and ask for product/category details only when they materially affect the output.',
  'Best-fit use cases: apparel, shoes, bags, jewelry, watches, eyewear, hats, accessories, wearable products, beauty items held/worn by a model, and brand/lifestyle model visuals even before a specific product is locked.',
  '',
  'Workflow:',
  '1. If images are provided, analyze product category, shape, color, material, texture, fit clues, style cues, readable brand/text, and what must stay faithful.',
  '2. If no images are provided, analyze the text brief: desired market, product/category hints, mood, price tier, audience, platform, and conversion goal. Treat missing details as creative space, not a hard failure.',
  '3. Decide whether the task is product-on-model, model persona exploration, styling direction exploration, or final production prompting.',
  '4. Extract or ask for high-impact missing information: target audience, model profile, styling scenario, product/category, number of looks, visual tone, platform/use case, body/fit requirements, and text/no-text preference.',
  '5. Provide 2-3 conversion-oriented styling directions by default. Each direction should be custom to the user brief, not a copied template.',
  '6. When ready, produce a production plan and image prompts for multiple model looks. Each look must have a clear audience, styling logic, pose, background, lighting, composition, commercial purpose, and quality/risk notes.',
  '7. Default output ratio is 9:16 vertical. If the user sets a batch count such as 4, keep one coherent campaign style but make each image meaningfully different: different model persona, pose, camera distance, scene detail, styling layer, expression, or product display angle.',
  '8. Always treat background as a fixed user decision for this skill. Ask whether to generate a background when it is not clear. If the user chooses no background, create a clean white studio/ecommerce backdrop only. If the user chooses background, match a scene/background to the selected styling direction.',
  '',
  'Styling direction intelligence:',
  '- Use style families only as inspiration, then customize them to the user brief and product/category.',
  '- 高端时尚: best for jewelry, watches, luxury bags, premium accessories, fragrance/beauty, designer apparel. Use sculptural poses, refined makeup, gallery/hotel/editorial settings, controlled highlights, elegant negative space, and understated confidence.',
  '- 活力青春: best for sportswear, sneakers, street fashion, backpacks, athleisure, campus/social commerce. Use dynamic motion, fresh color accents, outdoor/street/studio-energy scenes, confident smiles, and action-led composition.',
  '- 甜美可爱: best for soft fashion, accessories, beauty, lifestyle gifts, pastel products, Gen Z social commerce. Use soft light, approachable expressions, playful poses, gentle colors, and intimate lifestyle scenes.',
  '- 轻熟通勤: best for coats, shirts, handbags, watches, eyewear, office-friendly apparel. Use clean tailoring, commuter/cafe/office scenes, composed posture, neutral palette, and practical elegance.',
  '- 极简高级: best for premium basics, monochrome apparel, skincare, eyewear, jewelry. Use restrained styling, precise silhouette, quiet luxury palette, clean background, and premium texture.',
  '- 户外机能: best for outdoor wear, bags, shoes, sports accessories, travel products. Use natural terrain, durable styling, movement, weather texture, and utility details.',
  '- 未来科技: best for tech wearables, performance fabrics, eyewear, smart accessories, modern beauty devices. Use cool lighting, clean lines, metallic/blue-gray accents, and sleek model direction.',
  '- 复古氛围: best for denim, leather goods, watches, eyewear, nostalgic fashion. Use warm film light, vintage props, relaxed poses, and texture-rich environments.',
  '- When the user asks for more options, create new tailored combinations instead of restarting the full workflow.',
  '',
  'Product and model styling strategy:',
  '- Preserve the exact product identity: color, silhouette, pattern, logo placement, material texture, hardware, proportions, and any visible distinctive details.',
  '- Use model diversity thoughtfully: age range, gender presentation, body type, skin tone, hair/makeup, and lifestyle should match the target market without stereotypes.',
  '- For fashion/apparel: specify fit, drape, styling layers, footwear/accessories, pose, full-body/half-body crop, motion, and fabric behavior.',
  '- For bags/accessories/jewelry: specify scale on body, hand/neck/ear/wrist placement, close-up detail shots, lifestyle context, and premium material highlights.',
  '- For beauty or wearable lifestyle items: focus on clean skin/hair/makeup styling, natural use gestures, close-up clarity, and believable commercial lighting.',
  '',
  'Conversion rules:',
  '- Every look should answer a buyer question: who is this for, when to wear/use it, why it looks desirable, and what product detail builds trust.',
  '- Prefer fashion editorial quality with ecommerce clarity: clean product visibility, flattering pose, useful negative space, consistent brand tone, and no clutter.',
  '- Generate multiple looks only when they are meaningfully different. Avoid superficial duplicates.',
  '- Batch generation rule: same brand mood, same color system, same product/category assumptions, but high variation across model identity, pose, crop, scene, and styling details.',
  '- Background rule: "不需要背景/白底/影棚/棚拍" means white or very light gray seamless studio background, clean ecommerce lighting, no lifestyle scene, no hotel/gallery/street/nature background. "需要背景/匹配背景/场景背景" means generate a coherent scene that supports the styling direction.',
  '- If there is no product image, recommend suitable product/category pairings for each styling direction, but label them as recommendations or assumptions rather than confirmed facts.',
  '- If exact model attributes are not provided, recommend safe, inclusive options and ask for confirmation only when it materially changes the result.',
  '',
  'Prompt rule:',
  '- Separate product preservation, model profile, styling/outfit, pose/action, scene/background, lighting/camera, composition/crop, platform ratio, copy/no-copy strategy, and negative constraints.',
  '- Do not invent unsupported claims such as slimming, medical, or performance effects. Do not alter body shape unrealistically. Avoid sexualized posing for ordinary ecommerce.',
  '- If product print/logo/text must be exact, warn that final text/logo precision may need post-production or reference-preserving image editing.',
].join('\n');

export function getCommerceAgentSkills(): CommerceAgentSkill[] {
  return [
    {
      id: AD_CREATIVE_SKILL_ID,
      title: '广告创意',
      description: '为 Instagram、Facebook、TikTok、LinkedIn、YouTube、Google Ads 及 X 设计平台适配广告创意。',
      iconKey: 'megaphone',
      promptInstructions: AD_CREATIVE_PROMPT_INSTRUCTIONS,
      requiredSlots: ['platforms', 'objective', 'visualDirection'],
      optionalSlots: ['audience', 'sellingPoint', 'cta', 'brandInfo', 'outputFormat'],
      slotLabels: {
        platforms: '投放平台',
        objective: '广告目标',
        visualDirection: '创意方向',
        audience: '目标受众',
        sellingPoint: '核心卖点',
        cta: 'CTA',
        brandInfo: '品牌信息',
        outputFormat: '输出格式',
      },
      slotAliases: {
        platforms: ['平台', '版位', '投放平台'],
        objective: ['目标', '广告目标', '投放目标'],
        visualDirection: ['风格', '创意方向', '视觉方向'],
        audience: ['人群', '受众', '目标用户'],
        sellingPoint: ['卖点', '核心卖点', '突出'],
        cta: ['CTA', '行动号召', '按钮'],
        brandInfo: ['品牌', '品牌名'],
        outputFormat: ['输出格式', '产物'],
      },
      workflowStages: ['collecting', 'planning', 'ready', 'refining', 'generating'],
      outputArtifacts: ['方案节点', '生成结果节点'],
      qualityChecklist: [
        '平台尺寸和安全区是否匹配',
        '主体和核心卖点是否清晰',
        '文案是否适合后期排版而非强依赖 AI 精确渲染',
      ],
      defaultQuestions: [
        {
          id: 'ad-platform',
          label: '你优先投放哪个平台或版位？',
          allowMultiple: true,
          options: [
            { id: 'instagram-feed', label: 'Instagram Feed', value: '平台：Instagram Feed' },
            { id: 'instagram-reels', label: 'Instagram Story/Reels', value: '平台：Instagram Story/Reels' },
            { id: 'facebook-feed', label: 'Facebook Feed', value: '平台：Facebook Feed' },
            { id: 'tiktok', label: 'TikTok', value: '平台：TikTok' },
            { id: 'linkedin', label: 'LinkedIn', value: '平台：LinkedIn' },
            { id: 'youtube', label: 'YouTube', value: '平台：YouTube' },
            { id: 'google-ads', label: 'Google Ads', value: '平台：Google Ads' },
            { id: 'x', label: 'X', value: '平台：X' },
            { id: 'multi-platform', label: '多平台组合', value: '平台：多平台组合' },
          ],
        },
        {
          id: 'ad-goal',
          label: '这次广告更看重什么目标？',
          allowMultiple: false,
          options: [
            { id: 'awareness', label: '品牌曝光', value: '目标：品牌曝光' },
            { id: 'traffic', label: '点击访问', value: '目标：点击访问' },
            { id: 'conversion', label: '转化下单', value: '目标：转化下单' },
            { id: 'lead', label: '留资咨询', value: '目标：留资咨询' },
          ],
        },
      ],
      quickOptions: [
        '先分析图片并推荐投放平台',
        '做一版多平台广告创意方案',
        '突出产品卖点和点击理由',
        '生成广告文案和画面提示词',
      ],
    },
    {
      id: AI_STYLIST_SKILL_ID,
      title: 'AI造型师:高转化模特图',
      description: '瞬时生成多款专业模特造型，全方位展现商品潜力，触达更广泛受众并提升销售转化。',
      iconKey: 'shirt',
      promptInstructions: AI_STYLIST_PROMPT_INSTRUCTIONS,
      requiredSlots: ['targetAudience', 'visualDirection'],
      optionalSlots: ['productCategory', 'modelProfile', 'stylingScenario', 'backgroundMode', 'productFit', 'lookCount', 'platforms', 'copyStrategy', 'brandInfo', 'outputFormat'],
      slotLabels: {
        targetAudience: '目标受众',
        productCategory: '商品/品类方向',
        modelProfile: '模特人设',
        stylingScenario: '造型场景',
        backgroundMode: '是否生成背景',
        productFit: '版型/佩戴重点',
        lookCount: '造型数量',
        visualDirection: '视觉风格',
        platforms: '使用平台',
        copyStrategy: '文案策略',
        brandInfo: '品牌信息',
        outputFormat: '输出格式',
      },
      slotAliases: {
        targetAudience: ['目标受众', '受众', '人群', '目标用户', '买家'],
        productCategory: ['商品', '产品', '品类', '类目', '货品', '搭配品类'],
        modelProfile: ['模特', '模特人设', '模特类型', '年龄', '性别', '肤色', '身材'],
        stylingScenario: ['场景', '穿搭场景', '造型场景', '使用场景', '风格场景'],
        backgroundMode: ['背景', '是否生成背景', '需要背景', '不需要背景', '白底', '影棚', '棚拍', '场景背景'],
        productFit: ['版型', '尺码', '穿着重点', '佩戴重点', '露出重点', '面料', '材质'],
        lookCount: ['几套', '数量', '造型数量', 'look', 'looks'],
        visualDirection: ['风格', '视觉风格', '造型方向', '拍摄风格'],
        platforms: ['平台', '使用平台', '版位', '投放平台'],
        copyStrategy: ['文案', '文字', '无文字', '标题', 'CTA'],
        brandInfo: ['品牌', '品牌名', '品牌调性'],
        outputFormat: ['输出格式', '产物', '比例', '尺寸'],
      },
      workflowStages: ['collecting', 'planning', 'ready', 'refining', 'generating'],
      outputArtifacts: ['方案节点', '生成结果节点'],
      qualityChecklist: [
        '商品颜色、廓形、材质、图案和关键细节是否保真',
        '模特人设、造型场景和目标受众是否匹配',
        '姿态与构图是否能清楚展示商品卖点',
        '多套造型是否有真实差异而不是重复换背景',
        '是否避免不真实身材、过度性感化、虚假功效或不合规表达',
      ],
      defaultQuestions: [
        {
          id: 'stylist-audience',
          label: '这组模特图优先打动哪类买家或品牌人群？',
          allowMultiple: false,
          options: [
            { id: 'urban-commuter', label: '都市通勤人群', value: '目标受众：都市通勤人群' },
            { id: 'young-social', label: '年轻社交穿搭', value: '目标受众：年轻社交穿搭人群' },
            { id: 'premium-quality', label: '品质精致用户', value: '目标受众：品质精致用户' },
            { id: 'outdoor-active', label: '户外/运动生活方式', value: '目标受众：户外/运动生活方式人群' },
          ],
        },
        {
          id: 'stylist-look-direction',
          label: '你想先探索哪类模特造型气质？',
          allowMultiple: true,
          options: [
            { id: 'luxury-fashion', label: '高端时尚', value: '造型方向：高端时尚；适合珠宝、腕表、奢侈品包袋、香氛美妆或高级成衣，强调精致姿态、材质高光和留白' },
            { id: 'youth-energy', label: '活力青春', value: '造型方向：活力青春；适合运动、潮流、校园、街头时尚类商品，强调动态姿势、明快色彩和社媒传播感' },
            { id: 'cute-sweet', label: '甜美可爱', value: '造型方向：甜美可爱；适合软萌服饰、配饰、美妆、礼品和年轻女性消费场景，强调亲和表情、柔和光线和轻松氛围' },
            { id: 'commuter-chic', label: '轻熟通勤', value: '造型方向：轻熟通勤；适合衬衫、大衣、包袋、腕表、眼镜等，强调干净剪裁、都市场景和实用高级感' },
            { id: 'minimal-premium', label: '极简高级', value: '造型方向：极简高级；适合基础款、高级配饰、护肤、眼镜和珠宝，强调克制构图、安静奢华和质感细节' },
            { id: 'outdoor-utility', label: '户外机能', value: '造型方向：户外机能；适合户外服饰、鞋包、运动配件和旅行产品，强调功能细节、自然环境和行动感' },
          ],
        },
        {
          id: 'stylist-background-mode',
          label: '这组模特图是否需要场景背景？',
          allowMultiple: false,
          options: [
            { id: 'no-background', label: '不需要背景', value: '背景：不需要背景，生成白色/浅灰无缝影棚背景，干净电商棚拍，不要生活方式场景' },
            { id: 'with-background', label: '需要背景', value: '背景：需要背景，请根据模特造型风格匹配合适的场景背景' },
          ],
        },
        {
          id: 'stylist-look-count',
          label: '先做几套差异化模特造型？',
          allowMultiple: false,
          options: [
            { id: 'three-looks', label: '3 套核心造型', value: '造型数量：3 套核心造型' },
            { id: 'five-looks', label: '5 套受众扩展', value: '造型数量：5 套受众扩展造型' },
            { id: 'platform-set', label: '按平台比例出图', value: '输出格式：按平台比例生成模特图组合' },
          ],
        },
      ],
      quickOptions: [
        '先看图并推荐适合的模特人设',
        '生成3套高转化模特造型方向',
        '突出商品版型、材质和穿搭场景',
        '做成高级杂志感模特图',
      ],
    },
  ];
}

export function getCommerceAgentSkill(skillId: string): CommerceAgentSkill | null {
  return getCommerceAgentSkills().find((skill) => skill.id === skillId) ?? null;
}

export function buildSkillGuidanceFallback(skill: CommerceAgentSkill): CommerceAdAgentGuidance {
  return {
    stage: 'brief',
    summary: `已启用「${skill.title}」，我会先看图，再按投放平台和广告目标补齐创意 Brief。`,
    confirmedFacts: [`技能：${skill.title}`],
    missingFields: ['投放平台', '广告目标', '目标受众', '核心卖点/优惠', 'CTA'],
    questions: skill.defaultQuestions,
    designDirections: [],
    quickReplies: skill.quickOptions,
    readinessHint: '选择一个平台或目标后，我会把它放进输入框，你可以再补充品牌和受众后发送。',
  };
}
